name: para_note_mobile
description: PARA note-taking mobile client.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.4.0
  go_router: ^14.1.0
  intl: ^0.19.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  domain_models:
    path: ../../../packages/domain_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.0
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
